"""initial_schema_83_tables

Revision ID: 84d7354d60b9
Revises: 
Create Date: 2026-03-26 16:59:03.372111

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '84d7354d60b9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auth_roles',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('auth_users',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('job_title', sa.String(), nullable=True),
    sa.Column('department', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('timezone', sa.String(), nullable=True),
    sa.Column('status', sa.String(), server_default='active', nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('catalog_destinations',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('code', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('country_code', sa.String(), nullable=True),
    sa.Column('region_name', sa.String(), nullable=True),
    sa.Column('city_name', sa.String(), nullable=True),
    sa.Column('timezone', sa.String(), nullable=True),
    sa.Column('latitude', sa.Numeric(), nullable=True),
    sa.Column('longitude', sa.Numeric(), nullable=True),
    sa.Column('status', sa.String(), server_default='active', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('catalog_hotel_amenities_master',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('code', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('catalog_restaurant_cuisines_master',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('code', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('catalog_tag_dimensions',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('ingestion_sources',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('source_code', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('source_type', sa.String(), nullable=False),
    sa.Column('domain', sa.String(), nullable=True),
    sa.Column('base_url', sa.Text(), nullable=True),
    sa.Column('ingestion_method', sa.String(), nullable=False),
    sa.Column('default_priority', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_code')
    )
    op.create_table('ops_freshness_rules',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('data_type', sa.String(), nullable=False),
    sa.Column('threshold_hours', sa.Integer(), nullable=False),
    sa.Column('stale_action', sa.String(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('data_type')
    )
    op.create_table('pricing_package_types',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('default_margin_pct', sa.Numeric(), nullable=True),
    sa.Column('min_nights', sa.Integer(), nullable=True),
    sa.Column('max_nights', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('ai_discovery_runs',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('triggered_by', sa.UUID(), nullable=False),
    sa.Column('raw_input', sa.String(), nullable=False),
    sa.Column('confirmed_destination_id', sa.UUID(), nullable=True),
    sa.Column('destination_search_status', sa.String(), nullable=False),
    sa.Column('seed_generation_status', sa.String(), nullable=True),
    sa.Column('categories_requested', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('ai_model_used', sa.String(), nullable=True),
    sa.Column('ahrefs_used', sa.Boolean(), nullable=True),
    sa.Column('approved_sources_used', sa.Boolean(), nullable=True),
    sa.Column('total_items_generated', sa.Integer(), nullable=True),
    sa.Column('total_items_approved', sa.Integer(), nullable=True),
    sa.Column('total_items_rejected', sa.Integer(), nullable=True),
    sa.Column('total_items_pushed', sa.Integer(), nullable=True),
    sa.Column('run_status', sa.String(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('seed_generation_started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('seed_generation_completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('pm_review_started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['confirmed_destination_id'], ['catalog_destinations.id'], ),
    sa.ForeignKeyConstraint(['triggered_by'], ['auth_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audit_audit_logs',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('actor_user_id', sa.UUID(), nullable=True),
    sa.Column('entity_type', sa.String(), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('old_data', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('new_data', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('metadata', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['auth_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('auth_user_roles',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('assigned_by', sa.UUID(), nullable=True),
    sa.Column('assigned_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_by'], ['auth_users.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['auth_roles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['auth_users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'role_id')
    )
    op.create_table('catalog_booking_sources',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=True),
    sa.Column('code', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('booking_mode', sa.String(), nullable=False),
    sa.Column('endpoint_url', sa.Text(), nullable=True),
    sa.Column('contact_email', sa.String(), nullable=True),
    sa.Column('contact_phone', sa.String(), nullable=True),
    sa.Column('margin_priority_score', sa.Numeric(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['ingestion_sources.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('catalog_locations',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('destination_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('address_text', sa.Text(), nullable=True),
    sa.Column('latitude', sa.Numeric(), nullable=True),
    sa.Column('longitude', sa.Numeric(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['destination_id'], ['catalog_destinations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('catalog_tags',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('dimension_id', sa.UUID(), nullable=False),
    sa.Column('parent_tag_id', sa.UUID(), nullable=True),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['dimension_id'], ['catalog_tag_dimensions.id'], ),
    sa.ForeignKeyConstraint(['parent_tag_id'], ['catalog_tags.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('ingestion_destination_intelligence_runs',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('destination_id', sa.UUID(), nullable=False),
    sa.Column('triggered_by', sa.UUID(), nullable=True),
    sa.Column('trigger_type', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('approved_by', sa.UUID(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['approved_by'], ['auth_users.id'], ),
    sa.ForeignKeyConstraint(['destination_id'], ['catalog_destinations.id'], ),
    sa.ForeignKeyConstraint(['triggered_by'], ['auth_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ingestion_source_category_coverage',
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('product_category', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['ingestion_sources.id'], ),
    sa.PrimaryKeyConstraint('source_id', 'product_category')
    )
    op.create_table('ingestion_source_legal_checklists',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('checklist_status', sa.String(), nullable=False),
    sa.Column('reviewed_by', sa.UUID(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['reviewed_by'], ['auth_users.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['ingestion_sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ingestion_source_terms_policy',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('tos_status', sa.String(), nullable=False),
    sa.Column('review_status', sa.String(), nullable=False),
    sa.Column('reviewed_by', sa.UUID(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['reviewed_by'], ['auth_users.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['ingestion_sources.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_id')
    )
    op.create_table('ops_api_audits',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('system_name', sa.String(), nullable=False),
    sa.Column('environment', sa.String(), nullable=False),
    sa.Column('bulk_upsert_supported', sa.Boolean(), nullable=True),
    sa.Column('idempotency_supported', sa.Boolean(), nullable=True),
    sa.Column('rollback_supported', sa.Boolean(), nullable=True),
    sa.Column('staging_supported', sa.Boolean(), nullable=True),
    sa.Column('audit_status', sa.String(), nullable=False),
    sa.Column('reviewed_by', sa.UUID(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['reviewed_by'], ['auth_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ops_notifications',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('notification_type', sa.String(), nullable=True),
    sa.Column('entity_type', sa.String(), nullable=True),
    sa.Column('entity_id', sa.UUID(), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), server_default='unread', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['auth_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pricing_package_rules',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('package_type_id', sa.UUID(), nullable=False),
    sa.Column('rule_name', sa.String(), nullable=False),
    sa.Column('rule_json', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('version_no', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['auth_users.id'], ),
    sa.ForeignKeyConstraint(['package_type_id'], ['pricing_package_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ai_discovery_destination_candidates',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('discovery_run_id', sa.UUID(), nullable=False),
    sa.Column('candidate_rank', sa.Integer(), nullable=False),
    sa.Column('destination_name', sa.String(), nullable=False),
    sa.Column('country', sa.String(), nullable=False),
    sa.Column('country_code', sa.String(), nullable=True),
    sa.Column('region', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('timezone', sa.String(), nullable=True),
    sa.Column('latitude', sa.Numeric(), nullable=True),
    sa.Column('longitude', sa.Numeric(), nullable=True),
    sa.Column('ai_confidence_score', sa.Numeric(), nullable=True),
    sa.Column('ai_reasoning', sa.Text(), nullable=True),
    sa.Column('is_selected', sa.Boolean(), nullable=True),
    sa.Column('selected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['discovery_run_id'], ['ai_discovery_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ai_discovery_seed_items',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('discovery_run_id', sa.UUID(), nullable=False),
    sa.Column('destination_id', sa.UUID(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('area', sa.String(), nullable=True),
    sa.Column('seed_payload_json', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('ai_confidence_score', sa.Numeric(), nullable=True),
    sa.Column('ai_notes', sa.Text(), nullable=True),
    sa.Column('ahrefs_search_volume', sa.Integer(), nullable=True),
    sa.Column('ai_generation_model', sa.String(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('review_status', sa.String(), nullable=False),
    sa.Column('reviewed_by', sa.UUID(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('pm_edits_json', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('pm_notes', sa.Text(), nullable=True),
    sa.Column('raw_record_id', sa.UUID(), nullable=True),
    sa.Column('pushed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['destination_id'], ['catalog_destinations.id'], ),
    sa.ForeignKeyConstraint(['discovery_run_id'], ['ai_discovery_runs.id'], ),
    sa.ForeignKeyConstraint(['raw_record_id'], ['ingestion_raw_records.id'], use_alter=True),
    sa.ForeignKeyConstraint(['reviewed_by'], ['auth_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('content_destination_keyword_sets',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('destination_id', sa.UUID(), nullable=False),
    sa.Column('intelligence_run_id', sa.UUID(), nullable=True),
    sa.Column('keyword_set_json', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['destination_id'], ['catalog_destinations.id'], ),
    sa.ForeignKeyConstraint(['intelligence_run_id'], ['ingestion_destination_intelligence_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ingestion_approved_source_lists',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('intelligence_run_id', sa.UUID(), nullable=False),
    sa.Column('destination_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('approved_by', sa.UUID(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['approved_by'], ['auth_users.id'], ),
    sa.ForeignKeyConstraint(['destination_id'], ['catalog_destinations.id'], ),
    sa.ForeignKeyConstraint(['intelligence_run_id'], ['ingestion_destination_intelligence_runs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('intelligence_run_id')
    )
    op.create_table('ingestion_destination_keywords',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('intelligence_run_id', sa.UUID(), nullable=False),
    sa.Column('destination_id', sa.UUID(), nullable=False),
    sa.Column('keyword', sa.Text(), nullable=False),
    sa.Column('product_category', sa.String(), nullable=False),
    sa.Column('search_intent', sa.String(), nullable=True),
    sa.Column('search_volume', sa.Integer(), nullable=True),
    sa.Column('keyword_difficulty', sa.Numeric(), nullable=True),
    sa.Column('ctr_estimate', sa.Numeric(), nullable=True),
    sa.Column('rank_order', sa.Integer(), nullable=True),
    sa.Column('peak_months', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('off_peak_months', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('seasonal_trend_json', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['destination_id'], ['catalog_destinations.id'], ),
    sa.ForeignKeyConstraint(['intelligence_run_id'], ['ingestion_destination_intelligence_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ingestion_destination_paa_questions',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('intelligence_run_id', sa.UUID(), nullable=False),
    sa.Column('destination_id', sa.UUID(), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('rank_order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['destination_id'], ['catalog_destinations.id'], ),
    sa.ForeignKeyConstraint(['intelligence_run_id'], ['ingestion_destination_intelligence_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ingestion_jobs',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('destination_id', sa.UUID(), nullable=False),
    sa.Column('intelligence_run_id', sa.UUID(), nullable=True),
    sa.Column('ai_discovery_run_id', sa.UUID(), nullable=True),
    sa.Column('triggered_by', sa.UUID(), nullable=True),
    sa.Column('trigger_type', sa.String(), nullable=False),
    sa.Column('run_type', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('total_records_fetched', sa.Integer(), nullable=True),
    sa.Column('total_errors', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ai_discovery_run_id'], ['ai_discovery_runs.id'], ),
    sa.ForeignKeyConstraint(['destination_id'], ['catalog_destinations.id'], ),
    sa.ForeignKeyConstraint(['intelligence_run_id'], ['ingestion_destination_intelligence_runs.id'], ),
    sa.ForeignKeyConstraint(['triggered_by'], ['auth_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ingestion_source_discovery_candidates',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('intelligence_run_id', sa.UUID(), nullable=False),
    sa.Column('source_name', sa.String(), nullable=True),
    sa.Column('domain', sa.String(), nullable=True),
    sa.Column('website_url', sa.Text(), nullable=True),
    sa.Column('source_type', sa.String(), nullable=True),
    sa.Column('domain_authority', sa.Numeric(), nullable=True),
    sa.Column('keyword_overlap_pct', sa.Numeric(), nullable=True),
    sa.Column('data_structure_score', sa.Numeric(), nullable=True),
    sa.Column('freshness_score', sa.Numeric(), nullable=True),
    sa.Column('tos_status', sa.String(), nullable=True),
    sa.Column('overall_score', sa.Numeric(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['intelligence_run_id'], ['ingestion_destination_intelligence_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ingestion_source_legal_checklist_items',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('legal_checklist_id', sa.UUID(), nullable=False),
    sa.Column('item_code', sa.String(), nullable=False),
    sa.Column('item_label', sa.String(), nullable=False),
    sa.Column('item_status', sa.String(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['legal_checklist_id'], ['ingestion_source_legal_checklists.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ops_booking_source_health_checks',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('booking_source_id', sa.UUID(), nullable=False),
    sa.Column('health_status', sa.String(), nullable=False),
    sa.Column('response_time_ms', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('checked_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['booking_source_id'], ['catalog_booking_sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ai_discovery_review_actions',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('discovery_run_id', sa.UUID(), nullable=False),
    sa.Column('seed_item_id', sa.UUID(), nullable=True),
    sa.Column('action_type', sa.String(), nullable=False),
    sa.Column('action_by', sa.UUID(), nullable=False),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('item_count', sa.Integer(), nullable=True),
    sa.Column('old_values', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('new_values', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['action_by'], ['auth_users.id'], ),
    sa.ForeignKeyConstraint(['discovery_run_id'], ['ai_discovery_runs.id'], ),
    sa.ForeignKeyConstraint(['seed_item_id'], ['ai_discovery_seed_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('catalog_products',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('destination_id', sa.UUID(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=False),
    sa.Column('canonical_source_id', sa.UUID(), nullable=True),
    sa.Column('source_record_key', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('publish_flag', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('data_confidence', sa.Numeric(), nullable=True),
    sa.Column('attribute_completeness_pct', sa.Numeric(), nullable=True),
    sa.Column('created_by_job_id', sa.UUID(), nullable=True),
    sa.Column('last_updated_by_job_id', sa.UUID(), nullable=True),
    sa.Column('dedupe_hash', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['canonical_source_id'], ['ingestion_sources.id'], ),
    sa.ForeignKeyConstraint(['created_by_job_id'], ['ingestion_jobs.id'], ),
    sa.ForeignKeyConstraint(['destination_id'], ['catalog_destinations.id'], ),
    sa.ForeignKeyConstraint(['last_updated_by_job_id'], ['ingestion_jobs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('ingestion_approved_source_list_items',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('approved_source_list_id', sa.UUID(), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('product_category', sa.String(), nullable=False),
    sa.Column('priority_rank', sa.Integer(), nullable=False),
    sa.Column('relevance_score', sa.Numeric(), nullable=True),
    sa.Column('tos_status', sa.String(), nullable=True),
    sa.Column('ingestion_method', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['approved_source_list_id'], ['ingestion_approved_source_lists.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['ingestion_sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ingestion_job_sources',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('product_category', sa.String(), nullable=False),
    sa.Column('priority_rank', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('records_fetched', sa.Integer(), nullable=True),
    sa.Column('errors_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['ingestion_jobs.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['ingestion_sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ingestion_raw_records',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('destination_id', sa.UUID(), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('source_record_id', sa.String(), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('product_category_predicted', sa.String(), nullable=True),
    sa.Column('raw_payload', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('normalized_payload', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('data_confidence', sa.Numeric(), nullable=True),
    sa.Column('tos_approved', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('dedupe_hash', sa.String(), nullable=True),
    sa.Column('ingestion_status', sa.String(), nullable=False),
    sa.Column('ingestion_origin', sa.String(), nullable=True),
    sa.Column('ai_discovery_item_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ai_discovery_item_id'], ['ai_discovery_seed_items.id'], use_alter=True),
    sa.ForeignKeyConstraint(['destination_id'], ['catalog_destinations.id'], ),
    sa.ForeignKeyConstraint(['job_id'], ['ingestion_jobs.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['ingestion_sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ops_error_queue',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=True),
    sa.Column('entity_type', sa.String(), nullable=True),
    sa.Column('entity_id', sa.UUID(), nullable=True),
    sa.Column('stage', sa.String(), nullable=True),
    sa.Column('error_code', sa.String(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('retry_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('max_retry_count', sa.Integer(), server_default='3', nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('assigned_to', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_to'], ['auth_users.id'], ),
    sa.ForeignKeyConstraint(['job_id'], ['ingestion_jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ops_job_metrics',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('metric_name', sa.String(), nullable=False),
    sa.Column('metric_value', sa.Numeric(), nullable=True),
    sa.Column('metric_unit', sa.String(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['ingestion_jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pricing_packages',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('destination_id', sa.UUID(), nullable=False),
    sa.Column('package_type_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('duration_label', sa.String(), nullable=True),
    sa.Column('nights', sa.Integer(), nullable=True),
    sa.Column('days', sa.Integer(), nullable=True),
    sa.Column('short_description', sa.Text(), nullable=True),
    sa.Column('long_description', sa.Text(), nullable=True),
    sa.Column('inclusions', sa.Text(), nullable=True),
    sa.Column('exclusions', sa.Text(), nullable=True),
    sa.Column('from_price', sa.Numeric(), nullable=True),
    sa.Column('currency_code', sa.String(), nullable=True),
    sa.Column('base_cost', sa.Numeric(), nullable=True),
    sa.Column('margin_pct', sa.Numeric(), nullable=True),
    sa.Column('floor_price', sa.Numeric(), nullable=True),
    sa.Column('display_price', sa.Numeric(), nullable=True),
    sa.Column('manual_price_override', sa.Numeric(), nullable=True),
    sa.Column('pricing_status', sa.String(), nullable=True),
    sa.Column('created_by_job_id', sa.UUID(), nullable=True),
    sa.Column('approved_by', sa.UUID(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['approved_by'], ['auth_users.id'], ),
    sa.ForeignKeyConstraint(['created_by_job_id'], ['ingestion_jobs.id'], ),
    sa.ForeignKeyConstraint(['destination_id'], ['catalog_destinations.id'], ),
    sa.ForeignKeyConstraint(['package_type_id'], ['pricing_package_types.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('publishing_push_batches',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('environment', sa.String(), nullable=False),
    sa.Column('batch_status', sa.String(), nullable=False),
    sa.Column('triggered_by', sa.UUID(), nullable=True),
    sa.Column('approved_by', sa.UUID(), nullable=True),
    sa.Column('triggered_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('records_created', sa.Integer(), nullable=True),
    sa.Column('records_updated', sa.Integer(), nullable=True),
    sa.Column('records_failed', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['approved_by'], ['auth_users.id'], ),
    sa.ForeignKeyConstraint(['job_id'], ['ingestion_jobs.id'], ),
    sa.ForeignKeyConstraint(['triggered_by'], ['auth_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('catalog_attraction_products',
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('attraction_type', sa.String(), nullable=True),
    sa.Column('address_text', sa.Text(), nullable=True),
    sa.Column('latitude', sa.Numeric(), nullable=True),
    sa.Column('longitude', sa.Numeric(), nullable=True),
    sa.Column('typical_visit_duration', sa.String(), nullable=True),
    sa.Column('minimum_age', sa.Integer(), nullable=True),
    sa.Column('ticket_price_from', sa.Numeric(), nullable=True),
    sa.Column('ticket_price_to', sa.Numeric(), nullable=True),
    sa.Column('currency_code', sa.String(), nullable=True),
    sa.Column('includes_text', sa.Text(), nullable=True),
    sa.Column('excludes_text', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['catalog_products.id'], ),
    sa.PrimaryKeyConstraint('product_id')
    )
    op.create_table('catalog_hotel_products',
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('star_rating', sa.Integer(), nullable=True),
    sa.Column('property_type', sa.String(), nullable=True),
    sa.Column('address_text', sa.Text(), nullable=True),
    sa.Column('latitude', sa.Numeric(), nullable=True),
    sa.Column('longitude', sa.Numeric(), nullable=True),
    sa.Column('check_in_time', sa.Time(), nullable=True),
    sa.Column('check_out_time', sa.Time(), nullable=True),
    sa.Column('cancellation_policy', sa.String(), nullable=True),
    sa.Column('net_rate_from', sa.Numeric(), nullable=True),
    sa.Column('currency_code', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['catalog_products.id'], ),
    sa.PrimaryKeyConstraint('product_id')
    )
    op.create_table('catalog_product_booking_sources',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('booking_source_id', sa.UUID(), nullable=False),
    sa.Column('priority_rank', sa.Integer(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('assigned_by', sa.UUID(), nullable=True),
    sa.Column('assigned_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_by'], ['auth_users.id'], ),
    sa.ForeignKeyConstraint(['booking_source_id'], ['catalog_booking_sources.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['catalog_products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('catalog_product_faqs',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('answer', sa.Text(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['catalog_products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('catalog_product_media',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('media_type', sa.String(), nullable=False),
    sa.Column('media_url', sa.Text(), nullable=False),
    sa.Column('alt_text', sa.Text(), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('is_primary', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['catalog_products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('catalog_product_schema_markup',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('schema_type', sa.String(), nullable=True),
    sa.Column('json_ld', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['catalog_products.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id')
    )
    op.create_table('catalog_product_status_history',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('old_status', sa.String(), nullable=True),
    sa.Column('new_status', sa.String(), nullable=True),
    sa.Column('changed_by', sa.UUID(), nullable=True),
    sa.Column('changed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['changed_by'], ['auth_users.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['catalog_products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('catalog_product_tag_suggestions',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('tag_id', sa.UUID(), nullable=False),
    sa.Column('confidence_score', sa.Numeric(), nullable=True),
    sa.Column('suggestion_source', sa.String(), nullable=True),
    sa.Column('suggestion_status', sa.String(), nullable=True),
    sa.Column('reviewed_by', sa.UUID(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['catalog_products.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by'], ['auth_users.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['catalog_tags.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('catalog_product_tags',
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('tag_id', sa.UUID(), nullable=False),
    sa.Column('assigned_by_user_id', sa.UUID(), nullable=True),
    sa.Column('assigned_method', sa.String(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_by_user_id'], ['auth_users.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['catalog_products.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['catalog_tags.id'], ),
    sa.PrimaryKeyConstraint('product_id', 'tag_id')
    )
    op.create_table('catalog_product_versions',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('version_no', sa.Integer(), nullable=False),
    sa.Column('snapshot_json', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('created_by_job_id', sa.UUID(), nullable=True),
    sa.Column('created_by_user_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_job_id'], ['ingestion_jobs.id'], ),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['auth_users.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['catalog_products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('catalog_restaurant_products',
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('cuisine_type_summary', sa.Text(), nullable=True),
    sa.Column('address_text', sa.Text(), nullable=True),
    sa.Column('latitude', sa.Numeric(), nullable=True),
    sa.Column('longitude', sa.Numeric(), nullable=True),
    sa.Column('price_range', sa.String(), nullable=True),
    sa.Column('avg_spend_per_person', sa.Numeric(), nullable=True),
    sa.Column('currency_code', sa.String(), nullable=True),
    sa.Column('reservation_required', sa.Boolean(), nullable=True),
    sa.Column('halal_certified', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['catalog_products.id'], ),
    sa.PrimaryKeyConstraint('product_id')
    )
    op.create_table('catalog_transfer_products',
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('transfer_type', sa.String(), nullable=True),
    sa.Column('origin_location_id', sa.UUID(), nullable=True),
    sa.Column('destination_location_id', sa.UUID(), nullable=True),
    sa.Column('vehicle_type', sa.String(), nullable=True),
    sa.Column('minimum_pax', sa.Integer(), nullable=True),
    sa.Column('maximum_pax', sa.Integer(), nullable=True),
    sa.Column('typical_duration', sa.String(), nullable=True),
    sa.Column('pricing_model', sa.String(), nullable=True),
    sa.Column('net_rate', sa.Numeric(), nullable=True),
    sa.Column('currency_code', sa.String(), nullable=True),
    sa.Column('meet_and_greet_included', sa.Boolean(), nullable=True),
    sa.Column('twenty_four_seven_available', sa.Boolean(), nullable=True),
    sa.Column('flight_monitoring', sa.Boolean(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['destination_location_id'], ['catalog_locations.id'], ),
    sa.ForeignKeyConstraint(['origin_location_id'], ['catalog_locations.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['catalog_products.id'], ),
    sa.PrimaryKeyConstraint('product_id')
    )
    op.create_table('content_content_generation_runs',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=True),
    sa.Column('model_name', sa.String(), nullable=False),
    sa.Column('prompt_version', sa.String(), nullable=True),
    sa.Column('input_payload', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('output_payload', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('generation_status', sa.String(), nullable=False),
    sa.Column('regeneration_attempt', sa.Integer(), server_default='1', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['ingestion_jobs.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['catalog_products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('content_product_content',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('primary_keyword', sa.Text(), nullable=True),
    sa.Column('secondary_keywords', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('short_description', sa.Text(), nullable=True),
    sa.Column('long_description', sa.Text(), nullable=True),
    sa.Column('meta_title', sa.String(), nullable=True),
    sa.Column('meta_description', sa.String(), nullable=True),
    sa.Column('content_hash', sa.String(), nullable=True),
    sa.Column('seo_status', sa.String(), nullable=True),
    sa.Column('generated_by_model', sa.String(), nullable=True),
    sa.Column('approved_by', sa.UUID(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['approved_by'], ['auth_users.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['catalog_products.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id')
    )
    op.create_table('ingestion_approved_source_list_audit',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('approved_source_list_id', sa.UUID(), nullable=False),
    sa.Column('source_list_item_id', sa.UUID(), nullable=True),
    sa.Column('action_type', sa.String(), nullable=False),
    sa.Column('old_priority_rank', sa.Integer(), nullable=True),
    sa.Column('new_priority_rank', sa.Integer(), nullable=True),
    sa.Column('old_values', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('new_values', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('changed_by', sa.UUID(), nullable=True),
    sa.Column('changed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['approved_source_list_id'], ['ingestion_approved_source_lists.id'], ),
    sa.ForeignKeyConstraint(['changed_by'], ['auth_users.id'], ),
    sa.ForeignKeyConstraint(['source_list_item_id'], ['ingestion_approved_source_list_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ingestion_raw_record_media',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('raw_record_id', sa.UUID(), nullable=False),
    sa.Column('media_type', sa.String(), nullable=True),
    sa.Column('media_url', sa.Text(), nullable=False),
    sa.Column('alt_text', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['raw_record_id'], ['ingestion_raw_records.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ops_product_freshness_status',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('data_type', sa.String(), nullable=False),
    sa.Column('last_checked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_stale', sa.Boolean(), nullable=False),
    sa.Column('action_status', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['catalog_products.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id', 'data_type')
    )
    op.create_table('ops_product_quality_checks',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('check_type', sa.String(), nullable=False),
    sa.Column('check_status', sa.String(), nullable=False),
    sa.Column('details_json', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('checked_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['catalog_products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pricing_package_components',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('package_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('component_type', sa.String(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('nights', sa.Integer(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('pricing_basis', sa.String(), nullable=True),
    sa.Column('base_cost', sa.Numeric(), nullable=True),
    sa.Column('currency_code', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['package_id'], ['pricing_packages.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['catalog_products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pricing_package_generation_runs',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('package_id', sa.UUID(), nullable=False),
    sa.Column('generation_type', sa.String(), nullable=True),
    sa.Column('input_payload', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('output_payload', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['package_id'], ['pricing_packages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pricing_package_itinerary_days',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('package_id', sa.UUID(), nullable=False),
    sa.Column('day_no', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['package_id'], ['pricing_packages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pricing_package_media',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('package_id', sa.UUID(), nullable=False),
    sa.Column('media_url', sa.Text(), nullable=False),
    sa.Column('is_primary', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['package_id'], ['pricing_packages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pricing_package_price_calculations',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('package_id', sa.UUID(), nullable=False),
    sa.Column('calculation_status', sa.String(), nullable=False),
    sa.Column('base_cost', sa.Numeric(), nullable=True),
    sa.Column('margin_pct', sa.Numeric(), nullable=True),
    sa.Column('floor_price', sa.Numeric(), nullable=True),
    sa.Column('display_price', sa.Numeric(), nullable=True),
    sa.Column('override_price', sa.Numeric(), nullable=True),
    sa.Column('component_snapshot', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['package_id'], ['pricing_packages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pricing_package_tags',
    sa.Column('package_id', sa.UUID(), nullable=False),
    sa.Column('tag_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['package_id'], ['pricing_packages.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['catalog_tags.id'], ),
    sa.PrimaryKeyConstraint('package_id', 'tag_id')
    )
    op.create_table('publishing_batch_approvals',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('push_batch_id', sa.UUID(), nullable=False),
    sa.Column('approval_status', sa.String(), nullable=False),
    sa.Column('diff_summary', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('approval_notes', sa.Text(), nullable=True),
    sa.Column('approved_by', sa.UUID(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['approved_by'], ['auth_users.id'], ),
    sa.ForeignKeyConstraint(['push_batch_id'], ['publishing_push_batches.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('push_batch_id')
    )
    op.create_table('publishing_push_batch_items',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('push_batch_id', sa.UUID(), nullable=False),
    sa.Column('entity_type', sa.String(), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('operation_type', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('external_record_id', sa.String(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['push_batch_id'], ['publishing_push_batches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('publishing_rollback_batches',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('original_push_batch_id', sa.UUID(), nullable=False),
    sa.Column('initiated_by', sa.UUID(), nullable=True),
    sa.Column('initiated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('rollback_status', sa.String(), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['initiated_by'], ['auth_users.id'], ),
    sa.ForeignKeyConstraint(['original_push_batch_id'], ['publishing_push_batches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('workflow_classification_results',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('raw_record_id', sa.UUID(), nullable=False),
    sa.Column('classifier_model', sa.String(), nullable=False),
    sa.Column('predicted_category', sa.String(), nullable=False),
    sa.Column('confidence_score', sa.Numeric(), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('routing_action', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['raw_record_id'], ['ingestion_raw_records.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('raw_record_id')
    )
    op.create_table('catalog_attraction_operating_hours',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('attraction_product_id', sa.UUID(), nullable=False),
    sa.Column('weekday', sa.Integer(), nullable=False),
    sa.Column('open_time', sa.Time(), nullable=True),
    sa.Column('close_time', sa.Time(), nullable=True),
    sa.Column('closed_flag', sa.Boolean(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['attraction_product_id'], ['catalog_attraction_products.product_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('catalog_attraction_ticket_types',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('attraction_product_id', sa.UUID(), nullable=False),
    sa.Column('ticket_type', sa.String(), nullable=False),
    sa.Column('price_from', sa.Numeric(), nullable=True),
    sa.Column('price_to', sa.Numeric(), nullable=True),
    sa.Column('currency_code', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['attraction_product_id'], ['catalog_attraction_products.product_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('catalog_hotel_board_types',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('hotel_product_id', sa.UUID(), nullable=False),
    sa.Column('board_type', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['hotel_product_id'], ['catalog_hotel_products.product_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('catalog_hotel_product_amenities',
    sa.Column('hotel_product_id', sa.UUID(), nullable=False),
    sa.Column('amenity_id', sa.UUID(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['amenity_id'], ['catalog_hotel_amenities_master.id'], ),
    sa.ForeignKeyConstraint(['hotel_product_id'], ['catalog_hotel_products.product_id'], ),
    sa.PrimaryKeyConstraint('hotel_product_id', 'amenity_id')
    )
    op.create_table('catalog_hotel_room_types',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('hotel_product_id', sa.UUID(), nullable=False),
    sa.Column('room_type', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['hotel_product_id'], ['catalog_hotel_products.product_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('catalog_restaurant_operating_hours',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('restaurant_product_id', sa.UUID(), nullable=False),
    sa.Column('weekday', sa.Integer(), nullable=False),
    sa.Column('open_time', sa.Time(), nullable=True),
    sa.Column('close_time', sa.Time(), nullable=True),
    sa.Column('closed_flag', sa.Boolean(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['restaurant_product_id'], ['catalog_restaurant_products.product_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('catalog_restaurant_product_cuisines',
    sa.Column('restaurant_product_id', sa.UUID(), nullable=False),
    sa.Column('cuisine_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cuisine_id'], ['catalog_restaurant_cuisines_master.id'], ),
    sa.ForeignKeyConstraint(['restaurant_product_id'], ['catalog_restaurant_products.product_id'], ),
    sa.PrimaryKeyConstraint('restaurant_product_id', 'cuisine_id')
    )
    op.create_table('content_content_review_queue',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('content_generation_run_id', sa.UUID(), nullable=False),
    sa.Column('queue_status', sa.String(), nullable=False),
    sa.Column('assigned_to', sa.UUID(), nullable=True),
    sa.Column('reviewed_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_to'], ['auth_users.id'], ),
    sa.ForeignKeyConstraint(['content_generation_run_id'], ['content_content_generation_runs.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['catalog_products.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by'], ['auth_users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id')
    )
    op.create_table('publishing_rollback_batch_items',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('rollback_batch_id', sa.UUID(), nullable=False),
    sa.Column('push_batch_item_id', sa.UUID(), nullable=False),
    sa.Column('entity_type', sa.String(), nullable=True),
    sa.Column('entity_id', sa.UUID(), nullable=True),
    sa.Column('rollback_action', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['push_batch_item_id'], ['publishing_push_batch_items.id'], ),
    sa.ForeignKeyConstraint(['rollback_batch_id'], ['publishing_rollback_batches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('workflow_attribute_mapping_runs',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('raw_record_id', sa.UUID(), nullable=False),
    sa.Column('classification_result_id', sa.UUID(), nullable=False),
    sa.Column('target_category', sa.String(), nullable=False),
    sa.Column('mapping_status', sa.String(), nullable=False),
    sa.Column('required_fields_count', sa.Integer(), nullable=True),
    sa.Column('mapped_fields_count', sa.Integer(), nullable=True),
    sa.Column('missing_fields_count', sa.Integer(), nullable=True),
    sa.Column('completeness_pct', sa.Numeric(), nullable=True),
    sa.Column('mapped_payload', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['classification_result_id'], ['workflow_classification_results.id'], ),
    sa.ForeignKeyConstraint(['raw_record_id'], ['ingestion_raw_records.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('raw_record_id')
    )
    op.create_table('workflow_classification_review_queue',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('raw_record_id', sa.UUID(), nullable=False),
    sa.Column('classification_result_id', sa.UUID(), nullable=False),
    sa.Column('queue_status', sa.String(), nullable=False),
    sa.Column('assigned_to', sa.UUID(), nullable=True),
    sa.Column('reviewed_by', sa.UUID(), nullable=True),
    sa.Column('final_category', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_to'], ['auth_users.id'], ),
    sa.ForeignKeyConstraint(['classification_result_id'], ['workflow_classification_results.id'], ),
    sa.ForeignKeyConstraint(['raw_record_id'], ['ingestion_raw_records.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by'], ['auth_users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('raw_record_id')
    )
    op.create_table('content_content_review_actions',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('content_review_queue_id', sa.UUID(), nullable=False),
    sa.Column('action_type', sa.String(), nullable=False),
    sa.Column('action_by', sa.UUID(), nullable=False),
    sa.Column('old_status', sa.String(), nullable=True),
    sa.Column('new_status', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('regeneration_attempt', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['action_by'], ['auth_users.id'], ),
    sa.ForeignKeyConstraint(['content_review_queue_id'], ['content_content_review_queue.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('workflow_attribute_enrichment_queue',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('raw_record_id', sa.UUID(), nullable=False),
    sa.Column('attribute_mapping_run_id', sa.UUID(), nullable=False),
    sa.Column('queue_status', sa.String(), nullable=False),
    sa.Column('assigned_to', sa.UUID(), nullable=True),
    sa.Column('reviewed_by', sa.UUID(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('missing_fields', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_to'], ['auth_users.id'], ),
    sa.ForeignKeyConstraint(['attribute_mapping_run_id'], ['workflow_attribute_mapping_runs.id'], ),
    sa.ForeignKeyConstraint(['raw_record_id'], ['ingestion_raw_records.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by'], ['auth_users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('raw_record_id')
    )
    op.create_table('workflow_classification_review_actions',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('classification_review_queue_id', sa.UUID(), nullable=False),
    sa.Column('action_type', sa.String(), nullable=False),
    sa.Column('action_by', sa.UUID(), nullable=False),
    sa.Column('old_status', sa.String(), nullable=True),
    sa.Column('new_status', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['action_by'], ['auth_users.id'], ),
    sa.ForeignKeyConstraint(['classification_review_queue_id'], ['workflow_classification_review_queue.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('workflow_classification_review_actions')
    op.drop_table('workflow_attribute_enrichment_queue')
    op.drop_table('content_content_review_actions')
    op.drop_table('workflow_classification_review_queue')
    op.drop_table('workflow_attribute_mapping_runs')
    op.drop_table('publishing_rollback_batch_items')
    op.drop_table('content_content_review_queue')
    op.drop_table('catalog_restaurant_product_cuisines')
    op.drop_table('catalog_restaurant_operating_hours')
    op.drop_table('catalog_hotel_room_types')
    op.drop_table('catalog_hotel_product_amenities')
    op.drop_table('catalog_hotel_board_types')
    op.drop_table('catalog_attraction_ticket_types')
    op.drop_table('catalog_attraction_operating_hours')
    op.drop_table('workflow_classification_results')
    op.drop_table('publishing_rollback_batches')
    op.drop_table('publishing_push_batch_items')
    op.drop_table('publishing_batch_approvals')
    op.drop_table('pricing_package_tags')
    op.drop_table('pricing_package_price_calculations')
    op.drop_table('pricing_package_media')
    op.drop_table('pricing_package_itinerary_days')
    op.drop_table('pricing_package_generation_runs')
    op.drop_table('pricing_package_components')
    op.drop_table('ops_product_quality_checks')
    op.drop_table('ops_product_freshness_status')
    op.drop_table('ingestion_raw_record_media')
    op.drop_table('ingestion_approved_source_list_audit')
    op.drop_table('content_product_content')
    op.drop_table('content_content_generation_runs')
    op.drop_table('catalog_transfer_products')
    op.drop_table('catalog_restaurant_products')
    op.drop_table('catalog_product_versions')
    op.drop_table('catalog_product_tags')
    op.drop_table('catalog_product_tag_suggestions')
    op.drop_table('catalog_product_status_history')
    op.drop_table('catalog_product_schema_markup')
    op.drop_table('catalog_product_media')
    op.drop_table('catalog_product_faqs')
    op.drop_table('catalog_product_booking_sources')
    op.drop_table('catalog_hotel_products')
    op.drop_table('catalog_attraction_products')
    op.drop_table('publishing_push_batches')
    op.drop_table('pricing_packages')
    op.drop_table('ops_job_metrics')
    op.drop_table('ops_error_queue')
    op.drop_table('ingestion_raw_records')
    op.drop_table('ingestion_job_sources')
    op.drop_table('ingestion_approved_source_list_items')
    op.drop_table('catalog_products')
    op.drop_table('ai_discovery_review_actions')
    op.drop_table('ops_booking_source_health_checks')
    op.drop_table('ingestion_source_legal_checklist_items')
    op.drop_table('ingestion_source_discovery_candidates')
    op.drop_table('ingestion_jobs')
    op.drop_table('ingestion_destination_paa_questions')
    op.drop_table('ingestion_destination_keywords')
    op.drop_table('ingestion_approved_source_lists')
    op.drop_table('content_destination_keyword_sets')
    op.drop_table('ai_discovery_seed_items')
    op.drop_table('ai_discovery_destination_candidates')
    op.drop_table('pricing_package_rules')
    op.drop_table('ops_notifications')
    op.drop_table('ops_api_audits')
    op.drop_table('ingestion_source_terms_policy')
    op.drop_table('ingestion_source_legal_checklists')
    op.drop_table('ingestion_source_category_coverage')
    op.drop_table('ingestion_destination_intelligence_runs')
    op.drop_table('catalog_tags')
    op.drop_table('catalog_locations')
    op.drop_table('catalog_booking_sources')
    op.drop_table('auth_user_roles')
    op.drop_table('audit_audit_logs')
    op.drop_table('ai_discovery_runs')
    op.drop_table('pricing_package_types')
    op.drop_table('ops_freshness_rules')
    op.drop_table('ingestion_sources')
    op.drop_table('catalog_tag_dimensions')
    op.drop_table('catalog_restaurant_cuisines_master')
    op.drop_table('catalog_hotel_amenities_master')
    op.drop_table('catalog_destinations')
    op.drop_table('auth_users')
    op.drop_table('auth_roles')
    # ### end Alembic commands ###
